#include "sprite.h"

const INT16U ALIGN4 _mode_IMG0000_CellIdx[]={
	   7,	SP_ROTATE0,	   0,	SP_ZOOM0,	   0,	SP_PBANK1,	SPBLEND_DISABLE,	SP_DEPTH1,	SP_PALETTE0,	SP_VSIZE32,	SP_HSIZE32,	SPVFLIP_DISABLE,	SPHFLIP_DISABLE,	SP_COLOR16,	SP_MOSAIC0,	SPBLEND_LEVEL0,	0,	SpriteNoGroupID,	SPLarge_DISABLE,	SPInterpolation_DISABLE,
	   8,	SP_ROTATE0,	  32,	SP_ZOOM0,	   0,	SP_PBANK1,	SPBLEND_DISABLE,	SP_DEPTH1,	SP_PALETTE0,	SP_VSIZE32,	SP_HSIZE32,	SPVFLIP_DISABLE,	SPHFLIP_DISABLE,	SP_COLOR16,	SP_MOSAIC0,	SPBLEND_LEVEL0,	0,	SpriteNoGroupID,	SPLarge_DISABLE,	SPInterpolation_DISABLE,
	   9,	SP_ROTATE0,	  64,	SP_ZOOM0,	   0,	SP_PBANK1,	SPBLEND_DISABLE,	SP_DEPTH1,	SP_PALETTE0,	SP_VSIZE32,	SP_HSIZE32,	SPVFLIP_DISABLE,	SPHFLIP_DISABLE,	SP_COLOR16,	SP_MOSAIC0,	SPBLEND_LEVEL0,	0,	SpriteNoGroupID,	SPLarge_DISABLE,	SPInterpolation_DISABLE,
	  10,	SP_ROTATE0,	  96,	SP_ZOOM0,	   0,	SP_PBANK1,	SPBLEND_DISABLE,	SP_DEPTH1,	SP_PALETTE0,	SP_VSIZE32,	SP_HSIZE32,	SPVFLIP_DISABLE,	SPHFLIP_DISABLE,	SP_COLOR16,	SP_MOSAIC0,	SPBLEND_LEVEL0,	0,	SpriteNoGroupID,	SPLarge_DISABLE,	SPInterpolation_DISABLE,
	0xffff, 0xffff };
const INT16U ALIGN4 _mode_IMG0001_CellIdx[]={
	  11,	SP_ROTATE0,	   0,	SP_ZOOM0,	   0,	SP_PBANK1,	SPBLEND_DISABLE,	SP_DEPTH1,	SP_PALETTE0,	SP_VSIZE32,	SP_HSIZE32,	SPVFLIP_DISABLE,	SPHFLIP_DISABLE,	SP_COLOR16,	SP_MOSAIC0,	SPBLEND_LEVEL0,	0,	SpriteNoGroupID,	SPLarge_DISABLE,	SPInterpolation_DISABLE,
	  12,	SP_ROTATE0,	  32,	SP_ZOOM0,	   0,	SP_PBANK1,	SPBLEND_DISABLE,	SP_DEPTH1,	SP_PALETTE0,	SP_VSIZE32,	SP_HSIZE32,	SPVFLIP_DISABLE,	SPHFLIP_DISABLE,	SP_COLOR16,	SP_MOSAIC0,	SPBLEND_LEVEL0,	0,	SpriteNoGroupID,	SPLarge_DISABLE,	SPInterpolation_DISABLE,
	  13,	SP_ROTATE0,	  64,	SP_ZOOM0,	   0,	SP_PBANK1,	SPBLEND_DISABLE,	SP_DEPTH1,	SP_PALETTE0,	SP_VSIZE32,	SP_HSIZE32,	SPVFLIP_DISABLE,	SPHFLIP_DISABLE,	SP_COLOR16,	SP_MOSAIC0,	SPBLEND_LEVEL0,	0,	SpriteNoGroupID,	SPLarge_DISABLE,	SPInterpolation_DISABLE,
	  14,	SP_ROTATE0,	  96,	SP_ZOOM0,	   0,	SP_PBANK1,	SPBLEND_DISABLE,	SP_DEPTH1,	SP_PALETTE0,	SP_VSIZE32,	SP_HSIZE32,	SPVFLIP_DISABLE,	SPHFLIP_DISABLE,	SP_COLOR16,	SP_MOSAIC0,	SPBLEND_LEVEL0,	0,	SpriteNoGroupID,	SPLarge_DISABLE,	SPInterpolation_DISABLE,
	0xffff, 0xffff };
const INT16U ALIGN4 _mode_IMG0002_CellIdx[]={
	  15,	SP_ROTATE0,	   0,	SP_ZOOM0,	   0,	SP_PBANK1,	SPBLEND_DISABLE,	SP_DEPTH1,	SP_PALETTE0,	SP_VSIZE32,	SP_HSIZE32,	SPVFLIP_DISABLE,	SPHFLIP_DISABLE,	SP_COLOR16,	SP_MOSAIC0,	SPBLEND_LEVEL0,	0,	SpriteNoGroupID,	SPLarge_DISABLE,	SPInterpolation_DISABLE,
	  16,	SP_ROTATE0,	  32,	SP_ZOOM0,	   0,	SP_PBANK1,	SPBLEND_DISABLE,	SP_DEPTH1,	SP_PALETTE0,	SP_VSIZE32,	SP_HSIZE32,	SPVFLIP_DISABLE,	SPHFLIP_DISABLE,	SP_COLOR16,	SP_MOSAIC0,	SPBLEND_LEVEL0,	0,	SpriteNoGroupID,	SPLarge_DISABLE,	SPInterpolation_DISABLE,
	  17,	SP_ROTATE0,	  64,	SP_ZOOM0,	   0,	SP_PBANK1,	SPBLEND_DISABLE,	SP_DEPTH1,	SP_PALETTE0,	SP_VSIZE32,	SP_HSIZE32,	SPVFLIP_DISABLE,	SPHFLIP_DISABLE,	SP_COLOR16,	SP_MOSAIC0,	SPBLEND_LEVEL0,	0,	SpriteNoGroupID,	SPLarge_DISABLE,	SPInterpolation_DISABLE,
	  18,	SP_ROTATE0,	  96,	SP_ZOOM0,	   0,	SP_PBANK1,	SPBLEND_DISABLE,	SP_DEPTH1,	SP_PALETTE0,	SP_VSIZE32,	SP_HSIZE32,	SPVFLIP_DISABLE,	SPHFLIP_DISABLE,	SP_COLOR16,	SP_MOSAIC0,	SPBLEND_LEVEL0,	0,	SpriteNoGroupID,	SPLarge_DISABLE,	SPInterpolation_DISABLE,
	0xffff, 0xffff };
const INT16U ALIGN4 _mode_IMG0003_CellIdx[]={
	  19,	SP_ROTATE0,	   0,	SP_ZOOM0,	   0,	SP_PBANK1,	SPBLEND_DISABLE,	SP_DEPTH1,	SP_PALETTE0,	SP_VSIZE32,	SP_HSIZE32,	SPVFLIP_DISABLE,	SPHFLIP_DISABLE,	SP_COLOR16,	SP_MOSAIC0,	SPBLEND_LEVEL0,	0,	SpriteNoGroupID,	SPLarge_DISABLE,	SPInterpolation_DISABLE,
	  20,	SP_ROTATE0,	  32,	SP_ZOOM0,	   0,	SP_PBANK1,	SPBLEND_DISABLE,	SP_DEPTH1,	SP_PALETTE0,	SP_VSIZE32,	SP_HSIZE32,	SPVFLIP_DISABLE,	SPHFLIP_DISABLE,	SP_COLOR16,	SP_MOSAIC0,	SPBLEND_LEVEL0,	0,	SpriteNoGroupID,	SPLarge_DISABLE,	SPInterpolation_DISABLE,
	  21,	SP_ROTATE0,	  64,	SP_ZOOM0,	   0,	SP_PBANK1,	SPBLEND_DISABLE,	SP_DEPTH1,	SP_PALETTE0,	SP_VSIZE32,	SP_HSIZE32,	SPVFLIP_DISABLE,	SPHFLIP_DISABLE,	SP_COLOR16,	SP_MOSAIC0,	SPBLEND_LEVEL0,	0,	SpriteNoGroupID,	SPLarge_DISABLE,	SPInterpolation_DISABLE,
	  22,	SP_ROTATE0,	  96,	SP_ZOOM0,	   0,	SP_PBANK1,	SPBLEND_DISABLE,	SP_DEPTH1,	SP_PALETTE0,	SP_VSIZE32,	SP_HSIZE32,	SPVFLIP_DISABLE,	SPHFLIP_DISABLE,	SP_COLOR16,	SP_MOSAIC0,	SPBLEND_LEVEL0,	0,	SpriteNoGroupID,	SPLarge_DISABLE,	SPInterpolation_DISABLE,
	0xffff, 0xffff };
const INT16U ALIGN4 _mode_IMG0004_CellIdx[]={
	  19,	SP_ROTATE0,	   0,	SP_ZOOM0,	   0,	SP_PBANK1,	SPBLEND_DISABLE,	SP_DEPTH1,	SP_PALETTE0,	SP_VSIZE32,	SP_HSIZE32,	SPVFLIP_DISABLE,	SPHFLIP_DISABLE,	SP_COLOR16,	SP_MOSAIC0,	SPBLEND_LEVEL0,	0,	SpriteNoGroupID,	SPLarge_DISABLE,	SPInterpolation_DISABLE,
	  20,	SP_ROTATE0,	  32,	SP_ZOOM0,	   0,	SP_PBANK1,	SPBLEND_DISABLE,	SP_DEPTH1,	SP_PALETTE0,	SP_VSIZE32,	SP_HSIZE32,	SPVFLIP_DISABLE,	SPHFLIP_DISABLE,	SP_COLOR16,	SP_MOSAIC0,	SPBLEND_LEVEL0,	0,	SpriteNoGroupID,	SPLarge_DISABLE,	SPInterpolation_DISABLE,
	  21,	SP_ROTATE0,	  64,	SP_ZOOM0,	   0,	SP_PBANK1,	SPBLEND_DISABLE,	SP_DEPTH1,	SP_PALETTE0,	SP_VSIZE32,	SP_HSIZE32,	SPVFLIP_DISABLE,	SPHFLIP_DISABLE,	SP_COLOR16,	SP_MOSAIC0,	SPBLEND_LEVEL0,	0,	SpriteNoGroupID,	SPLarge_DISABLE,	SPInterpolation_DISABLE,
	  23,	SP_ROTATE0,	  96,	SP_ZOOM0,	   0,	SP_PBANK1,	SPBLEND_DISABLE,	SP_DEPTH1,	SP_PALETTE0,	SP_VSIZE32,	SP_HSIZE32,	SPVFLIP_DISABLE,	SPHFLIP_DISABLE,	SP_COLOR16,	SP_MOSAIC0,	SPBLEND_LEVEL0,	0,	SpriteNoGroupID,	SPLarge_DISABLE,	SPInterpolation_DISABLE,
	0xffff, 0xffff };
const INT16U ALIGN4 _mode_IMG0005_CellIdx[]={
	  24,	SP_ROTATE0,	   0,	SP_ZOOM0,	   0,	SP_PBANK1,	SPBLEND_DISABLE,	SP_DEPTH1,	SP_PALETTE0,	SP_VSIZE32,	SP_HSIZE32,	SPVFLIP_DISABLE,	SPHFLIP_DISABLE,	SP_COLOR16,	SP_MOSAIC0,	SPBLEND_LEVEL0,	0,	SpriteNoGroupID,	SPLarge_DISABLE,	SPInterpolation_DISABLE,
	  25,	SP_ROTATE0,	  32,	SP_ZOOM0,	   0,	SP_PBANK1,	SPBLEND_DISABLE,	SP_DEPTH1,	SP_PALETTE0,	SP_VSIZE32,	SP_HSIZE32,	SPVFLIP_DISABLE,	SPHFLIP_DISABLE,	SP_COLOR16,	SP_MOSAIC0,	SPBLEND_LEVEL0,	0,	SpriteNoGroupID,	SPLarge_DISABLE,	SPInterpolation_DISABLE,
	  26,	SP_ROTATE0,	  64,	SP_ZOOM0,	   0,	SP_PBANK1,	SPBLEND_DISABLE,	SP_DEPTH1,	SP_PALETTE0,	SP_VSIZE32,	SP_HSIZE32,	SPVFLIP_DISABLE,	SPHFLIP_DISABLE,	SP_COLOR16,	SP_MOSAIC0,	SPBLEND_LEVEL0,	0,	SpriteNoGroupID,	SPLarge_DISABLE,	SPInterpolation_DISABLE,
	  26,	SP_ROTATE0,	  96,	SP_ZOOM0,	   0,	SP_PBANK1,	SPBLEND_DISABLE,	SP_DEPTH1,	SP_PALETTE0,	SP_VSIZE32,	SP_HSIZE32,	SPVFLIP_DISABLE,	SPHFLIP_DISABLE,	SP_COLOR16,	SP_MOSAIC0,	SPBLEND_LEVEL0,	0,	SpriteNoGroupID,	SPLarge_DISABLE,	SPInterpolation_DISABLE,
	0xffff, 0xffff };
const SPRITE ALIGN4 mode_SP[]={ 
 { 0, 0, 0, 128, 32, 0, 0, 0, 0, 0, 0, 0, 0, (const INT32U *)_mode_IMG0000_CellIdx }, 
 { 0, 0, 0, 128, 32, 1, 0, 0, 0, 0, 0, 0, 0, (const INT32U *)_mode_IMG0001_CellIdx }, 
 { 0, 0, 0, 128, 32, 2, 0, 0, 0, 0, 0, 0, 0, (const INT32U *)_mode_IMG0002_CellIdx }, 
 { 0, 0, 0, 128, 32, 3, 0, 0, 0, 0, 0, 0, 0, (const INT32U *)_mode_IMG0003_CellIdx }, 
 { 0, 0, 0, 128, 32, 4, 0, 0, 0, 0, 0, 0, 0, (const INT32U *)_mode_IMG0004_CellIdx }, 
 { 0, 0, 0, 128, 32, 5, 0, 0, 0, 0, 0, 0, 0, (const INT32U *)_mode_IMG0005_CellIdx } 
};
const INT16U ALIGN4 _char_IMG0000_CellIdx[]={
	   1,	SP_ROTATE0,	   0,	SP_ZOOM0,	   0,	SP_PBANK3,	SPBLEND_DISABLE,	SP_DEPTH1,	SP_PALETTE0,	SP_VSIZE16,	SP_HSIZE16,	SPVFLIP_DISABLE,	SPHFLIP_DISABLE,	SP_COLOR16,	SP_MOSAIC0,	SPBLEND_LEVEL0,	0,	SpriteNoGroupID,	SPLarge_DISABLE,	SPInterpolation_DISABLE,
	   2,	SP_ROTATE0,	   0,	SP_ZOOM0,	  16,	SP_PBANK3,	SPBLEND_DISABLE,	SP_DEPTH1,	SP_PALETTE0,	SP_VSIZE16,	SP_HSIZE16,	SPVFLIP_DISABLE,	SPHFLIP_DISABLE,	SP_COLOR16,	SP_MOSAIC0,	SPBLEND_LEVEL0,	0,	SpriteNoGroupID,	SPLarge_DISABLE,	SPInterpolation_DISABLE,
	0xffff, 0xffff };
const INT16U ALIGN4 _char_IMG0001_CellIdx[]={
	   3,	SP_ROTATE0,	   0,	SP_ZOOM0,	   0,	SP_PBANK3,	SPBLEND_DISABLE,	SP_DEPTH1,	SP_PALETTE0,	SP_VSIZE16,	SP_HSIZE16,	SPVFLIP_DISABLE,	SPHFLIP_DISABLE,	SP_COLOR16,	SP_MOSAIC0,	SPBLEND_LEVEL0,	0,	SpriteNoGroupID,	SPLarge_DISABLE,	SPInterpolation_DISABLE,
	   4,	SP_ROTATE0,	   0,	SP_ZOOM0,	  16,	SP_PBANK3,	SPBLEND_DISABLE,	SP_DEPTH1,	SP_PALETTE0,	SP_VSIZE16,	SP_HSIZE16,	SPVFLIP_DISABLE,	SPHFLIP_DISABLE,	SP_COLOR16,	SP_MOSAIC0,	SPBLEND_LEVEL0,	0,	SpriteNoGroupID,	SPLarge_DISABLE,	SPInterpolation_DISABLE,
	0xffff, 0xffff };
const INT16U ALIGN4 _char_IMG0002_CellIdx[]={
	   5,	SP_ROTATE0,	   0,	SP_ZOOM0,	   0,	SP_PBANK3,	SPBLEND_DISABLE,	SP_DEPTH1,	SP_PALETTE0,	SP_VSIZE16,	SP_HSIZE16,	SPVFLIP_DISABLE,	SPHFLIP_DISABLE,	SP_COLOR16,	SP_MOSAIC0,	SPBLEND_LEVEL0,	0,	SpriteNoGroupID,	SPLarge_DISABLE,	SPInterpolation_DISABLE,
	   6,	SP_ROTATE0,	   0,	SP_ZOOM0,	  16,	SP_PBANK3,	SPBLEND_DISABLE,	SP_DEPTH1,	SP_PALETTE0,	SP_VSIZE16,	SP_HSIZE16,	SPVFLIP_DISABLE,	SPHFLIP_DISABLE,	SP_COLOR16,	SP_MOSAIC0,	SPBLEND_LEVEL0,	0,	SpriteNoGroupID,	SPLarge_DISABLE,	SPInterpolation_DISABLE,
	0xffff, 0xffff };
const INT16U ALIGN4 _char_IMG0003_CellIdx[]={
	   7,	SP_ROTATE0,	   0,	SP_ZOOM0,	   0,	SP_PBANK3,	SPBLEND_DISABLE,	SP_DEPTH1,	SP_PALETTE0,	SP_VSIZE16,	SP_HSIZE16,	SPVFLIP_DISABLE,	SPHFLIP_DISABLE,	SP_COLOR16,	SP_MOSAIC0,	SPBLEND_LEVEL0,	0,	SpriteNoGroupID,	SPLarge_DISABLE,	SPInterpolation_DISABLE,
	   8,	SP_ROTATE0,	   0,	SP_ZOOM0,	  16,	SP_PBANK3,	SPBLEND_DISABLE,	SP_DEPTH1,	SP_PALETTE0,	SP_VSIZE16,	SP_HSIZE16,	SPVFLIP_DISABLE,	SPHFLIP_DISABLE,	SP_COLOR16,	SP_MOSAIC0,	SPBLEND_LEVEL0,	0,	SpriteNoGroupID,	SPLarge_DISABLE,	SPInterpolation_DISABLE,
	0xffff, 0xffff };
const INT16U ALIGN4 _char_IMG0004_CellIdx[]={
	   9,	SP_ROTATE0,	   0,	SP_ZOOM0,	   0,	SP_PBANK3,	SPBLEND_DISABLE,	SP_DEPTH1,	SP_PALETTE0,	SP_VSIZE16,	SP_HSIZE16,	SPVFLIP_DISABLE,	SPHFLIP_DISABLE,	SP_COLOR16,	SP_MOSAIC0,	SPBLEND_LEVEL0,	0,	SpriteNoGroupID,	SPLarge_DISABLE,	SPInterpolation_DISABLE,
	  10,	SP_ROTATE0,	   0,	SP_ZOOM0,	  16,	SP_PBANK3,	SPBLEND_DISABLE,	SP_DEPTH1,	SP_PALETTE0,	SP_VSIZE16,	SP_HSIZE16,	SPVFLIP_DISABLE,	SPHFLIP_DISABLE,	SP_COLOR16,	SP_MOSAIC0,	SPBLEND_LEVEL0,	0,	SpriteNoGroupID,	SPLarge_DISABLE,	SPInterpolation_DISABLE,
	0xffff, 0xffff };
const INT16U ALIGN4 _char_IMG0005_CellIdx[]={
	  11,	SP_ROTATE0,	   0,	SP_ZOOM0,	   0,	SP_PBANK3,	SPBLEND_DISABLE,	SP_DEPTH1,	SP_PALETTE0,	SP_VSIZE16,	SP_HSIZE16,	SPVFLIP_DISABLE,	SPHFLIP_DISABLE,	SP_COLOR16,	SP_MOSAIC0,	SPBLEND_LEVEL0,	0,	SpriteNoGroupID,	SPLarge_DISABLE,	SPInterpolation_DISABLE,
	  12,	SP_ROTATE0,	   0,	SP_ZOOM0,	  16,	SP_PBANK3,	SPBLEND_DISABLE,	SP_DEPTH1,	SP_PALETTE0,	SP_VSIZE16,	SP_HSIZE16,	SPVFLIP_DISABLE,	SPHFLIP_DISABLE,	SP_COLOR16,	SP_MOSAIC0,	SPBLEND_LEVEL0,	0,	SpriteNoGroupID,	SPLarge_DISABLE,	SPInterpolation_DISABLE,
	0xffff, 0xffff };
const INT16U ALIGN4 _char_IMG0006_CellIdx[]={
	  13,	SP_ROTATE0,	   0,	SP_ZOOM0,	   0,	SP_PBANK3,	SPBLEND_DISABLE,	SP_DEPTH1,	SP_PALETTE0,	SP_VSIZE16,	SP_HSIZE16,	SPVFLIP_DISABLE,	SPHFLIP_DISABLE,	SP_COLOR16,	SP_MOSAIC0,	SPBLEND_LEVEL0,	0,	SpriteNoGroupID,	SPLarge_DISABLE,	SPInterpolation_DISABLE,
	  14,	SP_ROTATE0,	   0,	SP_ZOOM0,	  16,	SP_PBANK3,	SPBLEND_DISABLE,	SP_DEPTH1,	SP_PALETTE0,	SP_VSIZE16,	SP_HSIZE16,	SPVFLIP_DISABLE,	SPHFLIP_DISABLE,	SP_COLOR16,	SP_MOSAIC0,	SPBLEND_LEVEL0,	0,	SpriteNoGroupID,	SPLarge_DISABLE,	SPInterpolation_DISABLE,
	0xffff, 0xffff };
const INT16U ALIGN4 _char_IMG0007_CellIdx[]={
	  15,	SP_ROTATE0,	   0,	SP_ZOOM0,	   0,	SP_PBANK3,	SPBLEND_DISABLE,	SP_DEPTH1,	SP_PALETTE0,	SP_VSIZE16,	SP_HSIZE16,	SPVFLIP_DISABLE,	SPHFLIP_DISABLE,	SP_COLOR16,	SP_MOSAIC0,	SPBLEND_LEVEL0,	0,	SpriteNoGroupID,	SPLarge_DISABLE,	SPInterpolation_DISABLE,
	  16,	SP_ROTATE0,	   0,	SP_ZOOM0,	  16,	SP_PBANK3,	SPBLEND_DISABLE,	SP_DEPTH1,	SP_PALETTE0,	SP_VSIZE16,	SP_HSIZE16,	SPVFLIP_DISABLE,	SPHFLIP_DISABLE,	SP_COLOR16,	SP_MOSAIC0,	SPBLEND_LEVEL0,	0,	SpriteNoGroupID,	SPLarge_DISABLE,	SPInterpolation_DISABLE,
	0xffff, 0xffff };
const INT16U ALIGN4 _char_IMG0008_CellIdx[]={
	  17,	SP_ROTATE0,	   0,	SP_ZOOM0,	   0,	SP_PBANK3,	SPBLEND_DISABLE,	SP_DEPTH1,	SP_PALETTE0,	SP_VSIZE16,	SP_HSIZE16,	SPVFLIP_DISABLE,	SPHFLIP_DISABLE,	SP_COLOR16,	SP_MOSAIC0,	SPBLEND_LEVEL0,	0,	SpriteNoGroupID,	SPLarge_DISABLE,	SPInterpolation_DISABLE,
	  18,	SP_ROTATE0,	   0,	SP_ZOOM0,	  16,	SP_PBANK3,	SPBLEND_DISABLE,	SP_DEPTH1,	SP_PALETTE0,	SP_VSIZE16,	SP_HSIZE16,	SPVFLIP_DISABLE,	SPHFLIP_DISABLE,	SP_COLOR16,	SP_MOSAIC0,	SPBLEND_LEVEL0,	0,	SpriteNoGroupID,	SPLarge_DISABLE,	SPInterpolation_DISABLE,
	0xffff, 0xffff };
const INT16U ALIGN4 _char_IMG0009_CellIdx[]={
	  19,	SP_ROTATE0,	   0,	SP_ZOOM0,	   0,	SP_PBANK3,	SPBLEND_DISABLE,	SP_DEPTH1,	SP_PALETTE0,	SP_VSIZE16,	SP_HSIZE16,	SPVFLIP_DISABLE,	SPHFLIP_DISABLE,	SP_COLOR16,	SP_MOSAIC0,	SPBLEND_LEVEL0,	0,	SpriteNoGroupID,	SPLarge_DISABLE,	SPInterpolation_DISABLE,
	  20,	SP_ROTATE0,	   0,	SP_ZOOM0,	  16,	SP_PBANK3,	SPBLEND_DISABLE,	SP_DEPTH1,	SP_PALETTE0,	SP_VSIZE16,	SP_HSIZE16,	SPVFLIP_DISABLE,	SPHFLIP_DISABLE,	SP_COLOR16,	SP_MOSAIC0,	SPBLEND_LEVEL0,	0,	SpriteNoGroupID,	SPLarge_DISABLE,	SPInterpolation_DISABLE,
	0xffff, 0xffff };
const SPRITE ALIGN4 char_SP[]={ 
 { 0, 0, 0, 16, 32, 0, 0, 0, 0, 0, 0, 0, 0, (const INT32U *)_char_IMG0000_CellIdx }, 
 { 0, 0, 0, 16, 32, 1, 0, 0, 0, 0, 0, 0, 0, (const INT32U *)_char_IMG0001_CellIdx }, 
 { 0, 0, 0, 16, 32, 2, 0, 0, 0, 0, 0, 0, 0, (const INT32U *)_char_IMG0002_CellIdx }, 
 { 0, 0, 0, 16, 32, 3, 0, 0, 0, 0, 0, 0, 0, (const INT32U *)_char_IMG0003_CellIdx }, 
 { 0, 0, 0, 16, 32, 4, 0, 0, 0, 0, 0, 0, 0, (const INT32U *)_char_IMG0004_CellIdx }, 
 { 0, 0, 0, 16, 32, 5, 0, 0, 0, 0, 0, 0, 0, (const INT32U *)_char_IMG0005_CellIdx }, 
 { 0, 0, 0, 16, 32, 6, 0, 0, 0, 0, 0, 0, 0, (const INT32U *)_char_IMG0006_CellIdx }, 
 { 0, 0, 0, 16, 32, 7, 0, 0, 0, 0, 0, 0, 0, (const INT32U *)_char_IMG0007_CellIdx }, 
 { 0, 0, 0, 16, 32, 8, 0, 0, 0, 0, 0, 0, 0, (const INT32U *)_char_IMG0008_CellIdx }, 
 { 0, 0, 0, 16, 32, 9, 0, 0, 0, 0, 0, 0, 0, (const INT32U *)_char_IMG0009_CellIdx } 
};
const SPRITE* SpritesPool[]={ 
	mode_SP,
	char_SP
};
