#ifndef __AP_USBD_H__
#define __AP_USBD_H__
#include "state_usb.h"

#if _PROJ_TYPE == _PROJ_TURNKEY

#if (DPF_H_V == DPF_800x480 || DPF_H_V == DPF_640x480 || DPF_H_V == DPF_720x480)

    #define C_USBD_DEPTH				2
	//#define C_USBD_BLENDING				12
	#define C_USBD_TITLE_BLENDING		15
	#define C_USBD_TITLE_BG_BLENDING	14
	#define C_USBD_OUTLINE_BLENDING		15
	#define C_USBD_BG_BLENDING			14
	#define C_USBD_START_X				160
	#define C_USBD_START_Y				102
	#define C_USBD_WIDTH				480
	#define C_USBD_HEIGHT				250

	//#define STRING_STORAGE_ID				"1/5"
	#define C_USBD_FONT_SIZE				FONT_HEIGHT_POP_WINDOW_TITLE
	#define C_USBD_TITLE_TEXT_COLOR  	COLOR_WHITE
	#define C_USBD_TITLE_BG_COLOR  		COLOR_BLACK
	#define C_USBD_TITLE_BG_HEIGHT  	38

	#define C_USBD_FRAME_BG_COLOR  		COLOR_WHITE
	#define C_USBD_OUTLINE_BOARD_COLOR	COLOR_BLACK
	#define C_USBD_OUTLINE_BOARD_WIDTH	2

	#define C_USBD_ASK_STRING_X			-160
	#define C_USBD_ASK_STRING_Y			80
	#define C_USBD_AFFIRM_STRING_X		-120
	#define C_USBD_AFFIRM_STRING_Y		20
	#define C_USBD_NEGATE_STRING_X		50
	#define C_USBD_NEGATE_STRING_Y		20

#elif DPF_H_V == DPF_800x600

	#define C_USBD_DEPTH				2
	//#define C_USBD_BLENDING				12
	#define C_USBD_TITLE_BLENDING		15
	#define C_USBD_TITLE_BG_BLENDING	14
	#define C_USBD_OUTLINE_BLENDING		15
	#define C_USBD_BG_BLENDING			14
	#define C_USBD_START_X				160
	#define C_USBD_START_Y				160
	#define C_USBD_WIDTH				480
	#define C_USBD_HEIGHT				250

	//#define STRING_STORAGE_ID				"1/5"
	#define C_USBD_FONT_SIZE				FONT_HEIGHT_POP_WINDOW_TITLE
	#define C_USBD_TITLE_TEXT_COLOR  	COLOR_WHITE
	#define C_USBD_TITLE_BG_COLOR  		COLOR_BLACK
	#define C_USBD_TITLE_BG_HEIGHT  	38

	#define C_USBD_FRAME_BG_COLOR  		COLOR_WHITE
	#define C_USBD_OUTLINE_BOARD_COLOR	COLOR_BLACK
	#define C_USBD_OUTLINE_BOARD_WIDTH	2

	#define C_USBD_ASK_STRING_X			-160
	#define C_USBD_ASK_STRING_Y			80
	#define C_USBD_AFFIRM_STRING_X		-120
	#define C_USBD_AFFIRM_STRING_Y		20
	#define C_USBD_NEGATE_STRING_X		50
	#define C_USBD_NEGATE_STRING_Y		20

#elif DPF_H_V == DPF_320x240
 	#define C_USBD_DEPTH				2
		//#define C_USBD_BLENDING				12
	#define C_USBD_TITLE_BLENDING		15
	#define C_USBD_TITLE_BG_BLENDING	14
	#define C_USBD_OUTLINE_BLENDING		15
	#define C_USBD_BG_BLENDING			14
	#define C_USBD_START_X				32
	#define C_USBD_START_Y				50
	#define C_USBD_WIDTH				256
	#define C_USBD_HEIGHT				140

		//#define STRING_STORAGE_ID				"1/5"
	#define C_USBD_FONT_SIZE				FONT_HEIGHT_POP_WINDOW_TITLE
	#define C_USBD_TITLE_TEXT_COLOR  	COLOR_WHITE
	#define C_USBD_TITLE_BG_COLOR  		COLOR_BLACK
	#define C_USBD_TITLE_BG_HEIGHT  		18

	#define C_USBD_FRAME_BG_COLOR  		COLOR_WHITE
	#define C_USBD_OUTLINE_BOARD_COLOR	COLOR_BLACK
	#define C_USBD_OUTLINE_BOARD_WIDTH	1

	#define C_USBD_ASK_STRING_X			-105
	#define C_USBD_ASK_STRING_Y			45
	#define C_USBD_AFFIRM_STRING_X		-70
	#define C_USBD_AFFIRM_STRING_Y		-5
	#define C_USBD_NEGATE_STRING_X		35
	#define C_USBD_NEGATE_STRING_Y		-5

#elif (DPF_H_V == DPF_480x234 || DPF_H_V == DPF_480x272)
 	#define C_USBD_DEPTH				2
		//#define C_USBD_BLENDING				12
	#define C_USBD_TITLE_BLENDING		15
	#define C_USBD_TITLE_BG_BLENDING	15
	#define C_USBD_OUTLINE_BLENDING		15
	#define C_USBD_BG_BLENDING			14
	#define C_USBD_START_X				113    //32
	#define C_USBD_START_Y				55    //70
	#define C_USBD_WIDTH				256
	#define C_USBD_HEIGHT				120 //160

		//#define STRING_STORAGE_ID				"1/5"
	#define C_USBD_FONT_SIZE				FONT_HEIGHT_POP_WINDOW_TITLE
	#define C_USBD_TITLE_TEXT_COLOR  	COLOR_WHITE
	#define C_USBD_TITLE_BG_COLOR  		COLOR_BLACK
	#define C_USBD_TITLE_BG_HEIGHT  		18

	#define C_USBD_FRAME_BG_COLOR  		COLOR_WHITE
	#define C_USBD_OUTLINE_BOARD_COLOR	COLOR_BLACK
	#define C_USBD_OUTLINE_BOARD_WIDTH	1

	#define C_USBD_ASK_STRING_X			-105
	#define C_USBD_ASK_STRING_Y			45
	#define C_USBD_AFFIRM_STRING_X		-70
	#define C_USBD_AFFIRM_STRING_Y		10
	#define C_USBD_NEGATE_STRING_X		35
	#define C_USBD_NEGATE_STRING_Y		10
#endif

#define C_USBD_TV_OUT_START_X				160
#define C_USBD_TV_OUT_START_Y				102
#define C_USBD_TV_WIDTH						480
#define C_USBD_TV_HEIGHT					250

#endif

#endif /*__AP_USBD_H__*/